<a href="https://colab.research.google.com/github/couleux/Matrix-Unary-Computations/blob/main/3RDQUARTER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.array([
    [3, 2, 1, 1, 0],
    [1, 4, 2, 0, 1],
    [2, 3, 4, 1, 0],
    [1, 1, 3, 5, 0],
    [0, 1, 2, 4, 3]
])

B = np.array([100, 150, 120, 110, 140])

In [ ]:
det_A = np.linalg.det(A)
if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    # Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    # Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    print("Solution (Unknowns):")
    print(X)

Solution (Unknowns):
[ 7.36462094 32.23826715 -1.62454874 15.05415162 16.93140794]


**Practice Problems**

Problem 1:

In [ ]:
A1 = np.array([
    [2, 1, -1],
    [-1, 3, 2],
    [1, -2, 4]
])

B1 = np.array([5, 6, 7])

det_A1 = np.linalg.det(A1)
if det_A1 == 0:
    print("Matrix A1 is singular and cannot be inverted!")
else:
    # Find the inverse of matrix A1
    A1_inv = np.linalg.inv(A1)

    # Solve for X using the matrix inverse method
    X1 = np.dot(A1_inv, B1)

    print("Solution (Unknowns):")
    print(X1)

Solution (Unknowns):
[2.64102564 1.61538462 1.8974359 ]


Problem 2:

In [ ]:
A2 = np.array([
    [5, 3, 1, 1, 0],
    [4, 6, 2, 0, 1],
    [2, 7, 3, 1, 0],
    [1, 2, 4, 5, 0],
    [3, 4, 5, 0, 6]
])

B2 = np.array([200, 300, 150, 120, 250])

det_A2 = np.linalg.det(A2)
if det_A2 == 0:
    print("Matrix A2 is singular and cannot be inverted!")
else:
    # Find the inverse of matrix A1
    A2_inv = np.linalg.inv(A2)

    # Solve for X using the matrix inverse method
    X2 = np.dot(A2_inv, B2)

    print("Solution (Unknowns):")
    print(X2)

Solution (Unknowns):
[ -23.86666667  137.6        -336.          242.53333333  241.86666667]


Problem 3:

In [ ]:
np.random.seed(42)
A3 = np.random.randint(1, 10, size=(7, 7))

B3 = np.random.randint(10, 100, size=7)

det_A3 = np.linalg.det(A3)
if det_A3 == 0:
    print("Matrix A3 is singular and cannot be inverted!")
else:
    # Find the inverse of matrix A1
    A3_inv = np.linalg.inv(A3)

    # Solve for X using the matrix inverse method
    X3 = np.dot(A3_inv, B3)

    print("Solution (Unknowns):")
    print(X3)

Solution (Unknowns):
[ 3.34311393 10.17152918  0.49079184 -7.33151821  2.0390622   4.06600776
 -6.40401666]


Problem 4:

In [ ]:
np.random.seed(42)
A4 = np.random.randint(1, 10, size=(5, 5))

B4 = np.random.randint(10, 100, size=5)

det_A4 = np.linalg.det(A4)
if det_A4 == 0:
    print("Matrix A4 is singular and cannot be inverted!")
else:
    # Find the inverse of matrix A1
    A4_inv = np.linalg.inv(A4)

    # Solve for X using the matrix inverse method
    X4 = np.dot(A4_inv, B4)

    print("Solution (Unknowns):")
    print(X4)

Solution (Unknowns):
[-22.91568627  -4.2496732   -2.85882353  20.22941176  23.30457516]


Problem 5:

In [ ]:
def solve_system(coefficients, constants):
    A = np.array(coefficients)
    B = np.array(constants)

    det_A = np.linalg.det(A)

    if det_A == 0:
      print("Matrix A is singular and cannot be inverted!")
    else:
      # Find the inverse of matrix A
      A_inv = np.linalg.inv(A)

      # Solve for X using the matrix inverse method
      X = np.dot(A_inv, B)

      return X

solution = solve_system(A, B)
print("Problem 5 solution:")
print(solution)

Problem 5 solution:
[ 7.36462094 32.23826715 -1.62454874 15.05415162 16.93140794]
